export const SEARCH_NEW_RESULTS = "SEARCH_NEW_RESULTS";
export const ADD_NEW_SEARCHED_ITEM = "ADD_NEW_SEARCHED_ITEM"
export const ADD_NEW_COMPARED_ITEM = "ADD_NEW_COMPARED_ITEM"
export const REMOVE_COMPARED_ITEM = "REMOVE_COMPARED_ITEM"